### ISSUE TITLE
Замечания по 1 лабе

### ISSUE THREAD

**Issue by nightnoryu** [beta442/study-automata#1]
## Правильность

Из мура в мили все ОК.
Наоборот не учитывается, что состояния формируются по уникальным переходам. По примеру из ТЗ:

![image](https://user-images.githubusercontent.com/40693425/195931132-0a08d856-c859-4508-8fa0-7bb4faa1b8cd.png)

Слева - правильный результат, справа - твой.

## Алгоритм

1. В паре мест используется список и поиск с линейной сложностью, хотя можно было бы использовать мапу со сложностью поиска близкой к линейной. Например, для хранения переходов.

https://github.com/beta442/study-automata/blob/7224ad191c115242c988bf20a2929a245beb14c8/convertion/include/Automata/MealyMooreTable.hpp#L316-L319

2. Вот тут лучше использовать `unordered_map`, т.к. нам не важен порядок, а жертвовать эффективностью не хочется

https://github.com/beta442/study-automata/blob/7224ad191c115242c988bf20a2929a245beb14c8/convertion/include/Automata/MealyMooreTable.hpp#L238

## Код

1. Красивое, но слишком плюсовое. В следующий раз так упарываться не стоит.
2. Использование двух (!) либ в данном случае ну очень избыточно.

**Comment by yogrr** [comment]
Сделано:
- обработка лишь уникальных `MealyState`'ов при mealy-to-moore
- для сигналов в `MooreTable` заиспользован `vector` -> поиск сигнала при moore-to-mealy за O(1)
